export default async function verifyDemo(page) {
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  const network = [], sockets = [], errors = [];
  page.on('request', request => network.push(request.url()));
  page.on('websocket', socket => sockets.push(socket.url()));
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width:1440,height:1000});
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.route('**/dist/config.js', route => route.fulfill({contentType:'text/javascript',body:'window.__APP_CONFIG__={convexUrl:"https://private-test.convex.cloud",auth0Domain:"private-test.auth0.com",auth0ClientId:"sample-client"}'}));
  await page.goto('http://127.0.0.1:4187/?demo=1');
  await page.evaluate(() => {
    localStorage.setItem('precortex.authHint', JSON.stringify({name:'Private account sentinel',email:'private@example.test'}));
    localStorage.setItem('@@auth0spajs@@sentinel', 'unchanged-test-value');
  });
  const storage = await page.evaluate(() => JSON.stringify(localStorage));
  await page.reload();
  assert(!(await page.locator('body').innerText()).includes('Private account sentinel'), 'Private account leaked');
  assert(await page.locator('#mainView .task-row').count() === 3, 'Inbox seed missing');
  await page.getByRole('button',{name:'Confirm the workshop venue',exact:true}).focus();
  await page.keyboard.press('Enter');
  assert(await page.getByRole('dialog').count() === 1, 'Inbox keyboard opening failed');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Apply example plan',exact:true}).click();
  await page.getByRole('button',{name:'3. See today 1'}).click();
  assert(await page.locator('#mainView').getByText('high priority',{exact:true}).count() === 1, 'Priority badge missing');
  await page.getByRole('button',{name:'Add example subtasks',exact:true}).click();
  await page.getByRole('button',{name:'Edit priority and date',exact:true}).click();
  assert(await page.locator('[data-action="edit-subtask-title"]').count() === 2, 'Breakdown failed');
  await page.locator('#modalPrioritySelect').selectOption('low');
  const today = await page.locator('#modalDueDateInput').inputValue();
  await page.locator('#modalDueDateInput').fill('2030-01-15');
  await page.keyboard.press('Tab');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Undo last change',exact:true}).click();
  await page.getByRole('button',{name:'Edit priority and date',exact:true}).click();
  assert(await page.locator('#modalDueDateInput').inputValue() === today, 'Date undo failed');
  assert(await page.locator('#modalPrioritySelect').inputValue() === 'low', 'Undo changed unrelated priority');
  await page.locator('#modalProjectSelect').selectOption('demo-project');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  await page.locator('[data-task-id="demo-venue"] [data-action="schedule-task"][data-destination="today"]').click();
  await page.locator('[data-task-id="demo-invites"] [data-action="schedule-task"][data-destination="tomorrow"]').click();
  await page.locator('[data-task-id="demo-reading"] [data-action="schedule-task"][data-destination="next-week"]').click();
  assert(await page.getByText('Inbox reviewed. Check Today to see what you chose to work on.',{exact:true}).count() === 1, 'Walkthrough completion missing');
  await page.getByRole('button',{name:'3. See today 1'}).click();
  await page.locator('#mainView [data-action="toggle"]').click();
  assert(await page.locator('#mainView .completed').count() === 1, 'Completion failed');
  await page.getByRole('button',{name:'Undo last change',exact:true}).click();
  assert(await page.locator('#mainView .completed').count() === 0, 'Completion undo failed');
  await page.reload();
  assert(await page.locator('#mainView .task-row').count() === 3, 'Reload did not reset');
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile overflow');
  assert(await page.locator('#mobileNav').evaluate(el => el.inert), 'Closed nav keyboard leakage');
  assert(await page.locator('#assistantPanel').evaluate(el => el.inert), 'Closed assistant keyboard leakage');
  await page.getByRole('button',{name:'2. Decide priorities'}).click();
  await page.getByRole('button',{name:'close assistant',exact:true}).focus();
  await page.keyboard.press('Shift+Tab');
  assert(await page.locator(':focus').getAttribute('data-action') === 'demo-breakdown', 'Drawer reverse trap failed');
  await page.keyboard.press('Tab');
  assert(await page.locator(':focus').getAttribute('data-action') === 'close-assistant', 'Drawer forward trap failed');
  await page.getByRole('button',{name:'Apply example plan',exact:true}).click();
  await page.getByRole('button',{name:'Edit priority and date',exact:true}).click();
  await page.locator('#modalPrioritySelect').selectOption('medium');
  await page.locator('#modalDueDateInput').fill('2030-02-01');
  await page.keyboard.press('Tab');
  const controls = page.getByRole('dialog').locator('button, input, select, textarea');
  await controls.last().focus(); await page.keyboard.press('Tab');
  assert(await controls.first().evaluate(el => el === document.activeElement), 'Modal focus trap failed');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.activeElement?.getAttribute('data-action') === 'demo-review');
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  assert(await page.evaluate(() => JSON.stringify(localStorage)) === storage, 'Demo altered account storage');
  assert(network.filter(url => /convex\.cloud|auth0\.com|api\.openai|anthropic/.test(url)).length === 0, 'Demo contacted account/AI backend');
  assert(sockets.length === 0, 'Demo opened a backend websocket');
  assert(errors.length === 0, errors.join('\n'));
  await page.unroute('**/dist/config.js');
  await page.evaluate(() => { localStorage.removeItem('precortex.authHint'); localStorage.removeItem('@@auth0spajs@@sentinel'); });
  await page.goto('http://127.0.0.1:4187/');
  assert(await page.locator('h1').evaluate(el => getComputedStyle(el).opacity === '1'), 'Reduced motion hides hero');
  await page.getByRole('button',{name:'Try the demo',exact:true}).click();
  assert(page.url().endsWith('?demo=1'), 'Landing entry failed');
  return { result:'PASS', checks: ['inbox keyboard','plan and priority badge','subtasks','date/priority edit and undo','project assignment','all inbox triaged','completion undo','reload reset','mobile overflow','hidden drawer inertness','modal focus trap','account storage unchanged','zero account/AI requests','zero websockets','zero page errors','landing entry and reduced motion'] };
}
